left_party<- c("Die Grünen – Die grüne Alternative (GRÜNE)","Sozialdemokratische Partei Österreich (SPÖ)",
               "Kommunistische Partei Österreichs (KPÖ)","JETZT - Liste Pilz (JETZT)",
               "Écologistes Confédérés pour l'organisation de luttes originales (Ecolo)",
               "Groen","Socialistische Partij Anders (sp.a)","Parti socialiste (PS)",
               "Partij van de Arbeid van België (PVDA) - Parti du Travail de Belgique (PTB)",
               "Българска социалистическа партия (БСП)","Алтернатива за българско възраждане (АБВ)",
               "Socijaldemokratska partija Hrvatske  (SDP)","Hrvatska seljačka stranka  (HSS)",
               "Građansko-liberalni savez (Glas)","Istarski demokratski sabor (IDS)",
               "Hrvatska narodna stranka – Liberalni demokrati (HNS)",
               "Samostalna demokratska srpska stranka (SDSS (Самостална демократска српска странка (СДСС)))",
               "Česká pirátská strana (Piráti)","Česká strana sociálně demokratická (ČSSD)",
               "Komunistická strana Čech a Moravy (KSČM)","Strana zelených (SZ)",
               "Enhedslisten – De rød-grønne (Ø)","Socialdemokratiet (A)","Socialistisk Folkeparti (F)",
               "Alternativet (Å)","Det Radikale Venstre (B)","Sotsiaaldemokraatlik Erakond (SDE)",
               "Eesti Keskerakond (KE)","Erakond Eestimaa Rohelised (EER)","Vasemmistoliitto (VAS)",
               "Vihreä liitto (VIHR)","Suomen Sosialidemokraattinen Puolue (SDP)","Parti Socialiste (PS)",
               "Europe Écologie-Les Verts (EELV)","La France Insoumise (FI)","Génération.s","Résistons! (R!)",
               "Mouvement radical (MR)","Parti Communiste Francais (PCF)","Lutte Ouvrière (LO)",
               "Nouveau Parti anticapitaliste (NPA)","Die Linke (Linke)","Bündnis 90 / Die Grünen (Grüne)",
               "Die PARTEI","Sozialdemokratische Partei Deutschlands (SPD)","Tierschutzpartei - Partei Mensch Umwelt Tierschutz",
               "Piratenpartei Deutschland (Piraten)","Κίνημα Δημοκρατών Σοσιαλιστών (ΚΙΔΗΣΟ)"
               , "Kομμουνιστικό Kόμμα Ελλάδας (KKΕ)",
               "Συνασπισμός Ριζοσπαστικής Αριστεράς (ΣΥ.ΡIΖ.Α)"
               ,"Το Ποτάμι"  ,  "Πανελλήνιο Σοσιαλιστικό ίνημα (ΠΑΣΟK)",          "Πλεύση Ελευθερίας","Λαϊκή Ενότητα (ΛΑ.E.)",
               "Párbeszéd Magyarországért (Párbeszéd)","Lehet Más a Politika (LMP)","Magyar Szocialista Párt (MSZP)","Demokratikus Koalíció (DK)","Magyar Liberális Párt (MLP)","Green Party","Solidarity - People Before Profit (Solidarity-PBP)","Sinn Féin (SF)",
               "Labour Party (LP)","Independents 4 Change","Social Democrats (Daonlathaigh Shóisialta)","Workers' Party (WP)",
               "Partito Democratico (PD)","Potere al Popolo (PaP)","Sinistra Italiana (SI)","Articolo 1 – Movimento Democratico e Progressista (MDP)","Possibile (P)","Italia dei Valori (IdV)","Zaļo un Zemnieku savienība (ZZS: Latvijas Zemnieku savienība (LZS) + Latvijas Zaļā partija (LZP))","Progresīvie","Sociāldemokrātiskā partija „Saskaņa“ (SDP)","Latvijas Krievu savienība (LKS)","Lietuvos valstiečių ir žaliųjų sąjunga (LVŽS)","Darbo partija (DP)","Lietuvos socialdemokratų partija (LSDP)","Lietuvos socialdemokratų darbo partija (LSDDP)","Lietuvos Žaliųjų Partija (LŽP)","Socialistische Partij (SP)","GroenLinks (GL)","Partij voor de Dieren (PvdD)","Partij van de Arbeid (PvdA)","Democraten 66 (D66)","Wiosna","Sojusz Lewicy Demokratycznej (SLD)","Unia Pracy",
               "Partia Roberta Biedronia","Partia Razem (Razem)","Partia Zieloni","Mniejszość Niemiecka","Samoobrona","Twój Ruch","Partido Socialista (PS)","Partido Comunista Português (PCP)","Pessoas-Animais-Natureza (PAN)","Bloco de Esquerda (BE)","Partido Ecologista 'os Verdes' (PEV)","LIVRE","Partidul Social Democrat (PSD)","PRO România (PRO)","Partidul Socialist Român (PSR)",
               "Partidul Verde (Verzil)","Partidul Ecologist Român (PER)","Smer – sociálna demokracia (Smer-SD)","Stranka Alenke Bratušek",
               "Lista Marjana Šarca (LMŠ)","Socialni demokrati (SD)","Levica","Stranka modernega centra (SMC)","Piratska stranka Slovenije (Pirati)","Andrej Čuš in Zeleni Slovenije (AČZS)","Verjamem","Pozitivna Slovenija (PS)","Partido Socialista Obrero Español (PSOE)","Ciudadanos - Partido de la Ciudadanía (C's)","Podemos","Esquerra Republicana de Catalunya (ERC)","Izquierda Unida (IU)",
               "Partido Animalista Contra el Maltrato Animal (PACMA)","Euskal Herria Bildu (EH Bildu)","Bloque Nacionalista Galego (BNG)",
               "Socialdemokratiska arbetarpartiet (SAP)","Vänsterpartiet (V)","Miljöpartiet de Gröna (MP)","Feministiskt initiativ (FI)",
               "Piratpartiet (PP)","Plaid Cymru – Party of Wales (PL-PW)","Green Party of England and Wales (GP)","Liberal Democrats (Lib Dem)","Scotish National Party (SNP)","Labour Party (Labour)","Social Democratic & Labour Party (SDLP)","Latvijas Sociālistiskā partija (LSP)","DENK")

right_party <- c("Freiheitliche Partei Österreichs (FPÖ)","Österreichische Volkspartei (ÖVP)",
                 "EU-Austrittspartei (EUAUS)","Nieuw-Vlaamse Alliantie (N-VA)",
                 "Open Vlaamse Liberalen en Democraten (Open Vld)","Centre démocrate humaniste (cdH)",
                 "DéFI - Démocrate Fédéraliste Indépendant","Christen-Democratisch en Vlaams (CD&V)",
                 "Mouvement Réformateur (MR)","Parti populaire - Personenpartij (PP)",
                 "Droite Citoyenne (DC)","Да България!","ВМРО – Българско Национално Движение",
                 "Демократи за силна България (ДСБ)","Граждани за европейско развитие на България (ГЕРБ)",
                 "Атака","Национален фронт за спасение на България (НФСБ)","Most nezavisnih lista (MOST)",
                 "Hrvatska konzervativna stranka (HKS)","Hrvatska demokratska zajednica (HDZ)",
                 "Bandić Milan 365 - Stranka rada i solidarnosti (BM365)",
                 "Bruna Esih – Zlatko Hasanbegović: Neovisni za Hrvatsku (NHR)","Hrvatska demokršćanska stranka (HDS)",
                 "Svoboda a přímá demokracie (SPD)","Občanská demokratická strana (ODS)","Starostové a nezávislí (STAN)",
                 "Křesťanská a demokratická unie - Československá strana lidová (KDU-ČSL)",
                 "Tradice Odpovědnost Prosperita 09 (TOP 09)","Strana svobodných občanů (Svobodní)",
                 "Dansk Folkeparti (O)","Venstre (V)","Det Konservative Folkeparti (C)","Nye Borgerlige (D)",
                 "Stram Kurs (P)","Liberal Alliance (I)","Kristendemokraterne (K)","Eesti Reformierakond (ER)",
                 "Eesti Konservatiivne Rahvaerakond (EKRE)","Isamaa (I)","Eesti Vabaerakond (EVA)","Perussuomalaiset (PS)",
                 "Kansallinen Kokoomus (KOK)","Kristillisdemokraatit (KD)","Sininen tulevaisuus (SIN)",
                 "Rassemblement national (RN (ex. Front National (FN)))","Les Républicains (LR)","Debout la France (DLF)",
                 "Mouvement Démocrate (MoDem)","Union Populaire Républicaine (UPR)","Union des Démocrates et Indépendants (UDI)",
                 "Agir","Les Patriotes (LP)","Alternative für Deutschland (AfD)","Freie Wähler (FW)",
                 "Christlich Demokratische Union (CDU)","Freie Demokratische Partei (FDP)","Familien-Partei Deutschlands",
                 "Christlich Soziale Union (CSU)","ÖDP - Ökologisch-Demokratische Partei","Die Republikaner (REP)",
                 "Nationaldemokratische Partei Deutschlands (NPD)","Bündnis C – Christen für Deutschland",
                 "Nέα Δημοκρατία (NΔ)"     ,"Λαϊκός Σύνδεσμος -Χρυσή Αυγή (ΛΣ-ΧΑ)", "Ελληνική Λύση","Ανεξάρτητοι Έλληνες (ΑΝΕΛ)",
                 "Λαϊκός Ορθόδοξος Συναγερμός (ΛΑ.Ο.Σ)",         "Εθνική Ενότητα",    
                 "Fidesz – Magyar Polgári Szövetség (FIDESZ)","Jobbik Magyarországért Mozgalom (JOBBIK)","Mi Hazánk Mozgalom (Mi Hazánk)",
                 "Kereszténydemokrata Néppárt (KDNP)","Fine Gael (FG)","Fianna Fáil (FF)","Renua Ireland (Renua)","Forza Italia (FI)",
                 "Lega (Lega Salvini Premier)","Fratelli d'Italia (FDI)","Unione di Centro (UDC)","Alternativa Popolare (AP)",
                 "Latvijas attīstībai (LA)","Nacionālā apvienība „Visu Latvijai!” – „Tēvzemei un Brīvībai/LNNK” (NA)","Vienotība (V)",
                 "Kustība Par! (Par!)","'Kam pieder valsts' (KPV LV)","Jaunā konservatīvā partija (JKP)","No sirds Latvijai (NSL)",
                 "Tėvynės sąjunga - Lietuvos krikščionys demokratai (TS-LKD)","Liberalų sąjūdis (LRLS)","Tvarka ir teisingumas (TT)",
                 "Lietuvos lenkų rinkimų akcija – Krikščioniškų šeimų sąjunga (LLRA–KŠS)","Christen-Democratisch Appèl (CDA)",
                 "Partij voor de Vrijheid (PVV)","Volkspartij voor Vrijheid en Democratie (VVD)","Forum voor Democratie (FvD)",
                 "Staatkundig Gereformeerde Partij (SGP)","Prawo i Sprawiedliwość (PiS)","Platforma Obywatelska (PO)","Kukuiz'15",
                 "Porozumienie",".Nowoczesna (.N)","Kongres Nowej Prawicy (KNP)","Solidarna Polska (SP)","Polskie Stronnictwo Ludowe (PSL)",
                 "Wolność","Ruch Narodowy (RN)","Centro Democrático e Social – Partido Popular (CDS-PP)","Partido Social Democrata (PSD)",
                 "Aliança","Basta!","Partido Democrático Republicano (PDR)","Partido Popular Monárquico (PPM)","Uniunea Salvați România (USR)",
                 "Uniunea Democrată Maghiară din România (UDMR - Romániai Magyar Demokrata Szövetség (RMDSZ))","Partidul Național Liberal (PNL)",
                 "Alianța Liberalilor și Democraților (ALDE)","Partidul România Mare (PRM)","Partidul Mișcarea Populară (PMP)","Partidul National Taranesc Creştin Democrat (PNȚ-CD)","Obyčajní Ľudia a nezávislé osobnosti (OĽaNO)","Sloboda a Solidarita (SaS)","Kresťanskodemokratické hnutie (KDH)","SME RODINA – Boris Kollár (SME RODINA)","SPOLU - občianska demokracia (SPOLU)","Slovenská národná strana (SNS)","Strana maďarskej komunity - Magyar Közösség Pártja (SMK-MPK)","Most–Híd","Kotleba – Ľudová strana Naše Slovensko (ĽSNS)","Slovenská demokratická a kresťanská únia – Demokratická strana (SDKÚ–DS)","Prosperita Slovenska (PS)","Slovenska demokratska stranka (SDS)","Slovenska nacionalna stranka (SNS)","Nova Slovenija - Krščanski demokrati (N.Si)","Slovenska ljudska stranka (SLS)","Glas za otroke in družine (ZA OTROKE!)","Vox","Partido Popular (PP)","Partit Demòcrata Europeo Català (PDeCAT)","Sverigedemokraterna (SD)","Kristdemokraterna (KD)","Moderata samlingspartiet (M)","Liberalerna (L)",
                 "Centerpartiet (C)","Conservative and Unionist Party (Conservative Party)","Brexit Party","Democratic Unionist Party (DUP)",
                 "UK Independence Party (UKIP)","Ulster Unionist Party (UUP)","British National Party (BNP)","Eesti Iseseisvuspartei (EIP)",
                 "Catholic Democrats (The National Party)","Noi con l'Italia (NcL)","Křesťanská a demokratická unie – Československá strana lidová (KDU-ČSL)")

central_party <- c("NEOS – Das Neue Österreich und Liberales Forum (NEOS)","Vlaams Belang (VB)",
                   "Движение за права и свободи (ДПС)","Воля","Зелените","Pametno","ANO 2011 (ANO)",
                   "Eesti 200","Suomen Keskusta (KESK)",
                   "Svenska folkpartiet i Finland (SFP (Suomen ruotsalainen kansanpuolue (RKP)))",
                   "La République En Marche (REM)","Ένωση Κεντρώων (EK)"   , "Momentum Mozgalom (Momentum)","Più Europa (+E)","Latvijas Reģionu apvienība (LRA)","Lietuvos centro partija (LCP)","50Plus","ChristenUnie (CU)","Unia Europejskich Demokratów (UED)","Partidul Libertății Unității și Solidarității (PLUS)","M10","Progresívne Slovensko","Progresívne Slovensko (PS)","Demokratična stranka upokojencev Slovenije (DeSUS)","Euzko Alderdi Jeltzalea (EAJ/PNV)","Unión Progreso y Democracia (UPyD)","Change UK – The Independent Group")

other_party <- c("Piraten","Živi zid","Magyar Kétfarkú Kutya Párt (MKKP)","Independent Alliance","Movimento 5 Stelle (M5S)",
                 "Kita","","Dobra država")